version: "2"
exclude_patterns:
  - "backend/models/"
  - "backend/**/*_test*"

plugins:
  golint:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
  tslint:
    enabled: true

