# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG GO_VERSION=1.22.0
ARG ALPINE_VERSION=3.19
FROM golang:$GO_VERSION-alpine$ALPINE_VERSION AS base

# app lives here
WORKDIR /app

# Set production environment
ENV ZQZ_ENV="development"

# Install packages needed to build gems
RUN apk add --no-cache libpq-dev curl-dev alpine-sdk bash

# Install Deps
RUN go install github.com/pressly/goose/v3/cmd/goose@latest && \
    go install github.com/volatiletech/sqlboiler/v4@latest && \
    go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@latest

# USER app

# Install application gems
COPY --link go.mod go.sum ./

# Copy application code
COPY --link . .

RUN go mod download && go mod verify

# Entrypoint prepares the database.
ENTRYPOINT ["./bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000

# Run the Application
CMD go run cmd/backend/main.go
