// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID            int32            `db:"id" json:"id"`
	Size          int32            `db:"size" json:"size"`
	Name          string           `db:"name" json:"name"`
	Alias         string           `db:"alias" json:"alias"`
	Hash          string           `db:"hash" json:"hash"`
	Slug          string           `db:"slug" json:"slug"`
	ContentType   string           `db:"content_type" json:"content_type"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	UserID        *int32           `db:"user_id" json:"user_id"`
	Private       bool             `db:"private" json:"private"`
	Comment       string           `db:"comment" json:"comment"`
	BytesReceived int32            `db:"bytes_received" json:"bytes_received"`
}

type SiteSetting struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

type Thumbnail struct {
	ID        int32            `db:"id" json:"id"`
	FileID    int32            `db:"file_id" json:"file_id"`
	Width     int32            `db:"width" json:"width"`
	Height    int32            `db:"height" json:"height"`
	Hash      string           `db:"hash" json:"hash"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID                  int32     `db:"id" json:"id"`
	Name                string    `db:"name" json:"name"`
	Email               string    `db:"email" json:"email"`
	Provider            string    `db:"provider" json:"provider"`
	ProviderID          string    `db:"provider_id" json:"provider_id"`
	Role                string    `db:"role" json:"role"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time `db:"updated_at" json:"updated_at"`
	DisplayTag          *string   `db:"display_tag" json:"display_tag"`
	Colour              *string   `db:"colour" json:"colour"`
	Banned              bool      `db:"banned" json:"banned"`
	MaxFileSizeOverride *int64    `db:"max_file_size_override" json:"max_file_size_override"`
}
