// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountBannedUsers(ctx context.Context) (int64, error)
	CountFiles(ctx context.Context) (int64, error)
	CountFilesByUserID(ctx context.Context, userID *int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateThumbnail(ctx context.Context, arg CreateThumbnailParams) (Thumbnail, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFile(ctx context.Context, id int32) error
	DeleteFilesByUserID(ctx context.Context, userID *int32) error
	DeleteThumbnail(ctx context.Context, id int32) error
	DeleteThumbnailsByFileID(ctx context.Context, fileID int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetFileByHash(ctx context.Context, hash string) (File, error)
	GetFileByID(ctx context.Context, id int32) (File, error)
	GetFileBySlug(ctx context.Context, slug string) (File, error)
	GetFileWithThumbnail(ctx context.Context, id int32) (GetFileWithThumbnailRow, error)
	GetFileWithThumbnailByHash(ctx context.Context, hash string) (GetFileWithThumbnailByHashRow, error)
	GetFileWithThumbnailBySlug(ctx context.Context, slug string) (GetFileWithThumbnailBySlugRow, error)
	GetSiteSetting(ctx context.Context, key string) (string, error)
	GetThumbnailByFileID(ctx context.Context, fileID int32) (Thumbnail, error)
	GetThumbnailsByFileID(ctx context.Context, fileID int32) ([]Thumbnail, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByProviderID(ctx context.Context, providerID string) (User, error)
	ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error)
	ListFilesByUserID(ctx context.Context, arg ListFilesByUserIDParams) ([]File, error)
	ListFilesVisibleToUser(ctx context.Context, arg ListFilesVisibleToUserParams) ([]File, error)
	ListFilesWithThumbnails(ctx context.Context, arg ListFilesWithThumbnailsParams) ([]ListFilesWithThumbnailsRow, error)
	ListPublicFiles(ctx context.Context, arg ListPublicFilesParams) ([]File, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error)
	SearchFilesVisibleToUser(ctx context.Context, arg SearchFilesVisibleToUserParams) ([]File, error)
	SearchPublicFiles(ctx context.Context, arg SearchPublicFilesParams) ([]File, error)
	SetSiteSetting(ctx context.Context, arg SetSiteSettingParams) error
	SetUserBanned(ctx context.Context, arg SetUserBannedParams) (User, error)
	SetUserMaxFileSize(ctx context.Context, arg SetUserMaxFileSizeParams) (User, error)
	TotalFileSize(ctx context.Context) (int64, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateThumbnail(ctx context.Context, arg UpdateThumbnailParams) (Thumbnail, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
