// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
)

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT value FROM site_settings WHERE key = $1
`

func (q *Queries) GetSiteSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSiteSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setSiteSetting = `-- name: SetSiteSetting :exec
INSERT INTO site_settings (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = $2
`

type SetSiteSettingParams struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

func (q *Queries) SetSiteSetting(ctx context.Context, arg SetSiteSettingParams) error {
	_, err := q.db.Exec(ctx, setSiteSetting, arg.Key, arg.Value)
	return err
}
