// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thumbnails.sql

package repository

import (
	"context"
)

const createThumbnail = `-- name: CreateThumbnail :one
INSERT INTO thumbnails (
    file_id,
    hash,
    width,
    height
) VALUES (
    $1, $2, $3, $4
) RETURNING id, file_id, width, height, hash, created_at
`

type CreateThumbnailParams struct {
	FileID int32  `db:"file_id" json:"file_id"`
	Hash   string `db:"hash" json:"hash"`
	Width  int32  `db:"width" json:"width"`
	Height int32  `db:"height" json:"height"`
}

func (q *Queries) CreateThumbnail(ctx context.Context, arg CreateThumbnailParams) (Thumbnail, error) {
	row := q.db.QueryRow(ctx, createThumbnail,
		arg.FileID,
		arg.Hash,
		arg.Width,
		arg.Height,
	)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Width,
		&i.Height,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteThumbnail = `-- name: DeleteThumbnail :exec
DELETE FROM thumbnails
WHERE id = $1
`

func (q *Queries) DeleteThumbnail(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteThumbnail, id)
	return err
}

const deleteThumbnailsByFileID = `-- name: DeleteThumbnailsByFileID :exec
DELETE FROM thumbnails
WHERE file_id = $1
`

func (q *Queries) DeleteThumbnailsByFileID(ctx context.Context, fileID int32) error {
	_, err := q.db.Exec(ctx, deleteThumbnailsByFileID, fileID)
	return err
}

const getThumbnailByFileID = `-- name: GetThumbnailByFileID :one
SELECT id, file_id, width, height, hash, created_at FROM thumbnails
WHERE file_id = $1 LIMIT 1
`

func (q *Queries) GetThumbnailByFileID(ctx context.Context, fileID int32) (Thumbnail, error) {
	row := q.db.QueryRow(ctx, getThumbnailByFileID, fileID)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Width,
		&i.Height,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getThumbnailsByFileID = `-- name: GetThumbnailsByFileID :many
SELECT id, file_id, width, height, hash, created_at FROM thumbnails
WHERE file_id = $1
`

func (q *Queries) GetThumbnailsByFileID(ctx context.Context, fileID int32) ([]Thumbnail, error) {
	rows, err := q.db.Query(ctx, getThumbnailsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thumbnail{}
	for rows.Next() {
		var i Thumbnail
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Width,
			&i.Height,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThumbnail = `-- name: UpdateThumbnail :one
UPDATE thumbnails
SET
    hash = COALESCE($1, hash),
    width = COALESCE($2, width),
    height = COALESCE($3, height)
WHERE id = $4
RETURNING id, file_id, width, height, hash, created_at
`

type UpdateThumbnailParams struct {
	Hash   *string `db:"hash" json:"hash"`
	Width  *int32  `db:"width" json:"width"`
	Height *int32  `db:"height" json:"height"`
	ID     int32   `db:"id" json:"id"`
}

func (q *Queries) UpdateThumbnail(ctx context.Context, arg UpdateThumbnailParams) (Thumbnail, error) {
	row := q.db.QueryRow(ctx, updateThumbnail,
		arg.Hash,
		arg.Width,
		arg.Height,
		arg.ID,
	)
	var i Thumbnail
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Width,
		&i.Height,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}
