// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
)

const countBannedUsers = `-- name: CountBannedUsers :one
SELECT COUNT(*) FROM users WHERE banned = true
`

func (q *Queries) CountBannedUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBannedUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    provider,
    provider_id,
    role,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
) RETURNING id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override
`

type CreateUserParams struct {
	Name       string `db:"name" json:"name"`
	Email      string `db:"email" json:"email"`
	Provider   string `db:"provider" json:"provider"`
	ProviderID string `db:"provider_id" json:"provider_id"`
	Role       string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Provider,
		arg.ProviderID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override FROM users
WHERE provider_id = $1 LIMIT 1
`

func (q *Queries) GetUserByProviderID(ctx context.Context, providerID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, providerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Provider,
			&i.ProviderID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayTag,
			&i.Colour,
			&i.Banned,
			&i.MaxFileSizeOverride,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserBanned = `-- name: SetUserBanned :one
UPDATE users
SET banned = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override
`

type SetUserBannedParams struct {
	ID     int32 `db:"id" json:"id"`
	Banned bool  `db:"banned" json:"banned"`
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserBanned, arg.ID, arg.Banned)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const setUserMaxFileSize = `-- name: SetUserMaxFileSize :one
UPDATE users
SET max_file_size_override = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override
`

type SetUserMaxFileSizeParams struct {
	ID                  int32  `db:"id" json:"id"`
	MaxFileSizeOverride *int64 `db:"max_file_size_override" json:"max_file_size_override"`
}

func (q *Queries) SetUserMaxFileSize(ctx context.Context, arg SetUserMaxFileSizeParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserMaxFileSize, arg.ID, arg.MaxFileSizeOverride)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($1, name),
    email = COALESCE($2, email),
    role = COALESCE($3, role),
    updated_at = NOW()
WHERE id = $4
RETURNING id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override
`

type UpdateUserParams struct {
	Name  *string `db:"name" json:"name"`
	Email *string `db:"email" json:"email"`
	Role  *string `db:"role" json:"role"`
	ID    int32   `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_tag = $1,
    colour = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, email, provider, provider_id, role, created_at, updated_at, display_tag, colour, banned, max_file_size_override
`

type UpdateUserProfileParams struct {
	DisplayTag *string `db:"display_tag" json:"display_tag"`
	Colour     *string `db:"colour" json:"colour"`
	ID         int32   `db:"id" json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayTag, arg.Colour, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
		&i.ProviderID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayTag,
		&i.Colour,
		&i.Banned,
		&i.MaxFileSizeOverride,
	)
	return i, err
}
