// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Files", testFiles)
	t.Run("Thumbnails", testThumbnails)
}

func TestDelete(t *testing.T) {
	t.Run("Files", testFilesDelete)
	t.Run("Thumbnails", testThumbnailsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Files", testFilesQueryDeleteAll)
	t.Run("Thumbnails", testThumbnailsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Files", testFilesSliceDeleteAll)
	t.Run("Thumbnails", testThumbnailsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Files", testFilesExists)
	t.Run("Thumbnails", testThumbnailsExists)
}

func TestFind(t *testing.T) {
	t.Run("Files", testFilesFind)
	t.Run("Thumbnails", testThumbnailsFind)
}

func TestBind(t *testing.T) {
	t.Run("Files", testFilesBind)
	t.Run("Thumbnails", testThumbnailsBind)
}

func TestOne(t *testing.T) {
	t.Run("Files", testFilesOne)
	t.Run("Thumbnails", testThumbnailsOne)
}

func TestAll(t *testing.T) {
	t.Run("Files", testFilesAll)
	t.Run("Thumbnails", testThumbnailsAll)
}

func TestCount(t *testing.T) {
	t.Run("Files", testFilesCount)
	t.Run("Thumbnails", testThumbnailsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Files", testFilesHooks)
	t.Run("Thumbnails", testThumbnailsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Files", testFilesInsert)
	t.Run("Files", testFilesInsertWhitelist)
	t.Run("Thumbnails", testThumbnailsInsert)
	t.Run("Thumbnails", testThumbnailsInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Files", testFilesReload)
	t.Run("Thumbnails", testThumbnailsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Files", testFilesReloadAll)
	t.Run("Thumbnails", testThumbnailsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Files", testFilesSelect)
	t.Run("Thumbnails", testThumbnailsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Files", testFilesUpdate)
	t.Run("Thumbnails", testThumbnailsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Files", testFilesSliceUpdateAll)
	t.Run("Thumbnails", testThumbnailsSliceUpdateAll)
}
